### PR TITLE
Overall AI upgrade

### PR DESCRIPTION
**Pull request by dnqbob**
Overall AI upgrade
1.  Update all AI States fixes to my current version:
1.1 Move repair code to "Statebase.cs" on code optimazing.
1.2 Fix a rare crash bug in "GroundState" and optimazing its threat scan && regrouping in AttackMoveState.
1.3 Army in GroundState now will try to reach for the short-game-required actors first when switching target.
1.4 Add retreat and repair for ProtectionState

2.  Add "PowerDownBotModuleCA". AI will try turn off power when powerdown and try restore it later.

3.  When AI uses GroundState army to attack move to a target, it will inform friendly player by using beacon.

### CODE REVIEW

**Comment by dnqbob** [comment]
Already tested in CA and no bug currently, but still need your test on it.

**Comment by GraionDilach** [comment]
Does this include https://github.com/OpenRA/OpenRA/pull/17997? From my own testings, that one leads to frequent lagspikes (mind you that I tested it in RA2 so it could be just the scale of pathfinding required for that feature, but might be able to trigger that on a 8P AI skirmish on a huge map already). The others play fine however.

**Comment by dnqbob** [comment]
> Does this include [OpenRA/OpenRA#17997](https://github.com/OpenRA/OpenRA/pull/17997)?

CA has already used my AI fixes here but it is a relatively old version, with some bugs and something that needs improvement and I changed long ago.

> From my own testings, that one leads to frequent lagspikes (mind you that I tested it in RA2 so it could be just the scale of pathfinding required for that feature, but might be able to trigger that on a 8P AI skirmish on a huge map already). The others play fine however.

Do you mean OpenRA-RA2? That is weird because SP(SC) don't have it, if we see terrain layer factor on PF.

And lagspike may caused by Protection State because it will PF directly to attacker, if your map is big and twisted the Protection State PF will also lag the game. So it is really Ground State causes that problem?

I also meet some bugs here such as squad units counting seems including dead units which make the squad always trigger the stuck check. I am look into it but I think this one won't cause lagspikes. Maybe?

**Comment by Inq8** [comment]
If I remember correctly, I didn't include the "bugfix" AI improvement updates because it had a serious performance impact & I couldn't find the cause.

However the initial version did work without noticible performance loss.

**Comment by dnqbob** [comment]
> If I remember correctly, I didn't include the "bugfix" AI improvement updates because it had a serious performance impact & I couldn't find the cause.
> 
> However the initial version did work without noticible performance loss.

On which maps and how to reproduce it?

I need to see the if this problem is still not excluded in my newest upgrade.

**Comment by dnqbob** [comment]
Try a 6v6 game and, yeah, frequent lagspikes. I need to look into probably both protection state and ground attack state

**Comment by GraionDilach** [comment]
@dnqbob I've applied all of your AI PRs on top of AS/Engine bleed for a local Valiant Shades test and OpenRA/OpenRA#17997 caused my lagspikes. The rest are fine and are a noticeable improvement. I didn't debugged the case properly though, so it could be anything within the scope of that PR.

**Comment by dnqbob** [comment]
> @dnqbob I've applied all of your AI PRs on top of AS/Engine bleed for a local Valiant Shades test and [OpenRA/OpenRA#17997](https://github.com/OpenRA/OpenRA/pull/17997) caused my lagspikes. The rest are fine and are a noticeable improvement. I didn't debugged the case properly though, so it could be anything within the scope of that PR.

got it. I will see what exactly the problem here.

**Comment by dnqbob** [comment]
@GraionDilach
@Inq8 

I think this performance bug is fixed now in my test.

The causes is `GetRandomAttackable(Squad owner)`, my gosh. The `AttackOrFleeFuzzy.Rush.CanAttack` is too costy and I even put it in a loop.

**Comment by dnqbob** [comment]
I need you to have a test at it to confirm it is no problem already.

Also you may find AI use beacon too much (If you think so I will remove the one in GroundAttackState)

**Comment by dnqbob** [comment]
@GraionDilach  if you find it ok and need to update it to ValiantShades, 
Just beware I have almost change the entire "GroundAttackMoveState", "GroundAttackState" and "GroundStateBased".

Thanks for your bug report and the debug information is very precise.

**Comment by dnqbob** [comment]
There is still some lagspikes, when AI is too many. It is probably causing by protection state, and I also find it happens in 'master' branch of CA which is my old version. And also happens in RV which is the AI state original version.

**Comment by dnqbob** [comment]
And I will do some explain about the old and new GroundAttackMove.

it is all comes to fix this [problem](https://github.com/OpenRA/OpenRA/issues/17327)

old version

It took @tovl idea and can handle some of the maps AI will get stuck. But to some very hardcore map such as:
capture
Even this idea and stuck check is not helpful. And double check to find the actor in middle is not that performance-friendly compared to original.


new version

So I came to this idea instead of old one:

Squad units will not all directly AttackMove to target, instead they regroup to a certain actor which will keep AttackMove pathfinding until death (then they will have a new leader), which can greatly increase the AI pathfinding performance and much less stucked in complex maps.

It should be even low-cost compared to the original AttackMove, when AI try to reach the target because AI don't even need to calculate the leader, and it can go though that hard map I post above. Even units are stuck and really cannot get out, the most of pathfindings will be small and only point to leader.

So if it is still bad at performance, I may need help on that because I will be really no idea about it.

**Comment by dnqbob** [comment]
@Inq8

Hi, dude, is this PR really OK for now on your testing?

No more performance problem (or better than before, I mean both original version and my old version for CA) already?

**Comment by Inq8** [comment]
It did seem better, however I will continue to stress test it. The AI does reorder a lot (beacons places) when I last tested it.

**Comment by dnqbob** [comment]
> It did seem better, however I will continue to stress test it. The AI does reorder a lot (beacons places) when I last tested it.

It seems that if attackforce&rush interval is short and AI can reach the squad number in a short time, the beacon will give out in spam. 

You can delete 
```
				// Inform human allies about AI's rush attack.
				owner.Bot.QueueOrder(new Order("PlaceBeacon", owner.SquadManager.Player.PlayerActor, Target.FromCell(owner.World, owner.TargetActor.Location), false)
				{ SuppressVisualFeedback = true });
```

in `GroundUnitsIdleState` to shut it down.

There is also an another problem I find after I look into the `SquadManagerBotModule`, which is AI has two ground squad, Rush squad & Assault squad. Sometimes the Rush squad can cover some of the Assault squad units, which makes both squad cannot reach target if they are heading towards different direction. 

`SquadManagerBotModule` really need some fixes and probably I will do it soon.

**Pull request merged**
